

CREATE TABLE IF NOT EXISTS usuario(
    cedula varchar  null,
    nombre VARCHAR  NULL,
    apellido VARCHAR  NULL,
	especialidad VARCHAR null,
    direccion VARCHAR  NULL,
    celular VARCHAR  NULL,
	fechaVisita varchar null
)

drop table usuario



CREATE TABLE IF NOT EXISTS mascota(
    codMascota INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	nombreAnimal varchar null,
    fechaNac VARCHAR NULL,
    genero VARCHAR NULL,
	raza varchar null,
	edad integer null,
	color VARCHAR null,
	responsable varchar null
)

drop table mascota
drop table mascota


create table if not exists fichaMedica(
	codigoFicha INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	fechaFicha varchar  null,
	responsable varchar  null,
	veterinario varchar  null,
	nivelSalud varchar  null,
	esterilizado boolean  null,
	codAnimal integer 
)

drop table fichaMedica


create table if not exists producto(
	codigoProduc varchar not null,
	nombreVacuna varchar not null,
	descripVacuna varchar not null,
	cantDisponibidad integer not null,
	NombreProveedor varchar not null
)


drop table producto

create table if not exists factura(
	codFactura varchar not null,
	codProducto varchar not null,
	cedulaCliente varchar not null,
	codigoFicha varchar not null
)